# Generated by Django 5.2.4 on 2025-08-09 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentsPortfolio',
            new_name='StudentsProfile',
        ),
    ]
